-- Vaihe 1 (KORJATTU): Tyhjennä tietokanta ja poista RLS molemmista tauluversioista
-- Säilytetään admin-käyttäjä: a23e60ea-5941-4de3-932f-b7974413f88f

-- Tyhjennä kaikki data (molemmat versiot)
DELETE FROM huolto_varaosat;
DELETE FROM laskut;
DELETE FROM huollot;
DELETE FROM "Huollot";
DELETE FROM laitteet;
DELETE FROM "Laitteet";
DELETE FROM varaosat;
DELETE FROM asiakkaat;
DELETE FROM yrityksen_asetukset;
DELETE FROM service_statuses;
DELETE FROM hinnoittelu_asetukset;
DELETE FROM takuu_asetukset;
DELETE FROM tekniikat;
DELETE FROM laite_valmistajat;
DELETE FROM alv_asetukset;
DELETE FROM maksutavat;
DELETE FROM lasku_asetukset;
DELETE FROM numerointi_asetukset;
DELETE FROM varasto_asetukset;
DELETE FROM ilmoitus_asetukset;
DELETE FROM user_roles WHERE user_id != 'a23e60ea-5941-4de3-932f-b7974413f88f';
DELETE FROM profiles WHERE user_id != 'a23e60ea-5941-4de3-932f-b7974413f88f';

-- Poista RLS MOLEMMISTA versioista (pienet JA isot kirjaimet)
ALTER TABLE IF EXISTS asiakkaat DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS laitteet DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Laitteet" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS huollot DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Huollot" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS laskut DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS varaosat DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS huolto_varaosat DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS yrityksen_asetukset DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS service_statuses DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS hinnoittelu_asetukset DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS takuu_asetukset DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tekniikat DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS laite_valmistajat DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS alv_asetukset DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS maksutavat DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS lasku_asetukset DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS numerointi_asetukset DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS varasto_asetukset DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ilmoitus_asetukset DISABLE ROW LEVEL SECURITY;