// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouuwdlpteiqbhclmqusk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91dXdkbHB0ZWlxYmhjbG1xdXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0Mzc3NTQsImV4cCI6MjA3NDAxMzc1NH0.SiFIBfOAA2IGE1Y5MpXzt5bYDuM4FBJwlF1k0r8vGQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});